[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.14.9"

[[constraint]]
  branch = "master"
  name = "github.com/coinbase/step"

[[constraint]]
  branch = "master"
  name = "github.com/google/gofuzz"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[prune]
  go-tests = true
  unused-packages = true
